package com.springapplication.blogappproject.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a blog post entity.
 * This class is mapped to the "posts" table in the database.
 * It includes fields for id, title, content, and description.
 * The title field is unique across all posts.
 */

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(
        name = "posts", uniqueConstraints = {@UniqueConstraint(columnNames = {"title"})}
)
public class Post {

    /**
     * Unique identifier for the post.
     * This field is auto-generated by the database.
     */

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Title of the post.
     * This field is required and must be unique.
     */
    @Column(name = "title", nullable = false)
    private String title;

    /**
     * Content of the post.
     * This field is required.
     */
    @Column(name = "content", nullable = false)
    private String content;

    /**
     * Description of the post.
     * This field is required.
     */
    @Column(name = "description", nullable = false)
    private String description;


}
